import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { Navigation } from '@/components/Navigation/Navigation'
import StyledComponentsRegistry from '@/lib/registry'
import { StylesProvider } from '@/style/StylesProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<StyledComponentsRegistry>
					<StylesProvider>
						<Navigation />
						<main className='main-app-container'>{children}</main>
					</StylesProvider>
				</StyledComponentsRegistry>
			</body>
		</html>
	)
}
